RAD_Assignment2/config/routes.rb
Rails.application.routes.draw do

  get 'session/new'
  get 'sessions/new'
  get 'users/new'
  
  #ROOT
  root 'pages#home'
  get 'pages/comment'
  get 'pages/submit'
  get 'pages/login'
  get 'pages/register'
  get 'pages/about'
  
  get './signup',    to: 'user#create'
  
  get './login',     to: 'session#new'
  post './login',    to: 'session#create'
  delete './logout', to: 'session#destroy'
  
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RAD_Assignment2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RAD_Assignment2/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_secure_password
  
    PASSWORD_FORMAT = /\A
    (?=.{10,})          # Must contain 10 or more characters
    (?=.*\d)           # Must contain a digit
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
    (?=.*[[:^alnum:]]) # Must contain a symbol
    /x
    
    #formatting for password

    USERNAME_FORMAT = /\A[a-z0-9A-Z\-_]{2,15}\z/ #Can contain lowercase and upercase letters, numbers, - and _, must be between 2 and 15 length
    
    #username formatting
    
    validates :username,
    :presence => true,
    :uniqueness => true,
    :format => USERNAME_FORMAT
    
    validates :password, 
    :presence => true, 
    :format => PASSWORD_FORMAT,
    :confirmation => true, 
    :on  => create 
    
    before_save :encrypt_password
    # before callback after the user object gets changed, so password is encrypted
    after_save :clear_password
    # after callback after the user object gets changed, so the plaintext password is cleared
    
    def encrypt_password
        if password.present?
            self.salt = BCrypt::Engine.generate_salt
            self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
        end
    end
    
    def clear_password
     self.password = nil
    end
    

end

RAD_Assignment2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #protect_from_forgery with :exception
    include SessionHelper
    helper :all
    protect_from_forgery
    
    
    
end

RAD_Assignment2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contact
  end
end

RAD_Assignment2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    users = Users.find_by(id: params[:session][:username].downcase)
    if users && users.authenticate((params[:session][:password]))
      log_in users
      redirect_to "/"
    else
      flash[:danger] = 'Invalid id/password'
      redirect_to '/login'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

RAD_Assignment2/app/controllers/users_controller.rb
class UsersController < ApplicationController  
  
ActiveRecord::Base.establish_connection(  
:adapter => "mysql2",  
:host => "localhost",  
:database => "rad2"  
)  
  def show
    @user = User.find(params[:username])
  end
  
  def new
    @user = User.new
  end
  
    def create
 
      
    user = User.new(user_params)
    if user.save
    session[:user_id] = user.id
    redirect_to '/'

        flash[:notice] = "You signed up successfully"
        flash[:color]= "valid"
        redirect_to '/'
        #lets the user know they succesfully signed up

      else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        #lets the user know they failed at signing up

      end
    end
    
    
    def login
    end
    
    private
      
      #form check for empty input
      def user_params
        params.require(:user).permit(:name, :password)
      end
    
 
end

RAD_Assignment2/app/helpers/application_helper.rb
module ApplicationHelper
end

RAD_Assignment2/app/helpers/pages_helper.rb
module PagesHelper
end

RAD_Assignment2/app/helpers/session_helper.rb
module SessionHelper
end

RAD_Assignment2/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def is_logged_in
        !current_user.nil
    end
        
end

RAD_Assignment2/app/helpers/users_helper.rb
module UsersHelper
end

RAD_Assignment2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <%= link_to root_path, :target => "_blank" do %>
            <%= image_tag asset_path("rmitlogo.jpg") %>
          <% end %>
            <%= link_to "Home", root_path %>
            <%= link_to "Comments", pages_comment_path %>
            <%= link_to "Submit", pages_submit_path %>
            <%= link_to "Login", pages_login_path %>
        </nav>
      </div>
    </header> 
    
    <footer>
      <%= link_to "API", "https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2" %>
      <%= link_to "About", pages_about_path %>
    </footer>
    
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

RAD_Assignment2/app/views/pages/about.html.erb
<h3>Created By</h3>
<ul>
    <li>Adrian Kristanto Wibowo (S3428814)</li>
    <li>Marco Tessari (S3382522)</li>
</ul>

RAD_Assignment2/app/views/pages/comments.html.erb
<% @page_title = "Comments" %>

RAD_Assignment2/app/views/pages/home.html.erb
<% @page_title = "Comments" %>

RAD_Assignment2/app/views/pages/login.html.erb
<% @page_title = "Login/Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <%= f.label :username%>
    <%= f.text_field :username, class: 'form-control'%> <br>
    
    <%= f.label :password%>
    <%= f.password_field :password%> <br>
    
    <%= f.submit :Signup %> <br>
  <% end %>
  
  <h1>Login</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username%> <br>
    
    <%= f.label :password %>
    <%= f.password_field :password%> <br>
    
    <%= f.submit :Login %> <br>
  <% end %>
</div>

RAD_Assignment2/app/views/pages/submit.html.erb
<% @page_title = "Submit a News" %>
<%= text_area(:comment, :text, cols: 40, rows: 20, required: true, minlength: 10, maxlength: 200)%><br>

<%= label_tag "News Source" %>
<%= text_field_tag 'source' %>

RAD_Assignment2/app/views/shared/register_error_alert.html.erb
<% if @user.errors.any? %>
<div id="error_messages">
    <div>
        The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    
    <div>
        <ul>
        <% @user.errors.messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>        
    </div>
</div>

<% end %>